server:
  port: 9001

spring:
  application:
    name: component-user
  jpa:
    hibenate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localdocker:5001/user
    username: user
    password: user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/

lombok:
  equalsAndHashCode:
    callSuper: call